get:	
	flutter pub get

gen:
	dart run build_runner build --delete-conflicting-outputs --verbose

translate:
	dart run slang

run:	
	flutter run

architecture-check:
	bash ./tool/check_architecture.sh