export enum BookingStatusReasonCode {
  CHECKOUT_CREATED_PENDING_PAYMENT = 'CHECKOUT_CREATED_PENDING_PAYMENT',
  CHECKOUT_CREATED_CONFIRMED = 'CHECKOUT_CREATED_CONFIRMED',
  PAYMENT_CONFIRMED_MOMO = 'PAYMENT_CONFIRMED_MOMO',
  PAYMENT_CONFIRMED_STRIPE = 'PAYMENT_CONFIRMED_STRIPE',
  PAYMENT_EXPIRED_AUTO_CANCEL = 'PAYMENT_EXPIRED_AUTO_CANCEL',
  PAYMENT_REFUND_MOMO_CANCELLED = 'PAYMENT_REFUND_MOMO_CANCELLED',
  PAYMENT_REFUND_STRIPE_CANCELLED = 'PAYMENT_REFUND_STRIPE_CANCELLED',
  EMPLOYEE_STARTED_SERVICE = 'EMPLOYEE_STARTED_SERVICE',
  EMPLOYEE_COMPLETED_SERVICE = 'EMPLOYEE_COMPLETED_SERVICE',
  EMPLOYEE_CANCELLED = 'EMPLOYEE_CANCELLED',
  LEGACY_STATUS_CHANGE = 'LEGACY_STATUS_CHANGE',
}
