import 'package:admin_panel/features/partner/products/domain/facility_image.entity.dart';
import 'package:admin_panel/features/partner/products/domain/review.entity.dart';
import 'package:admin_panel/features/partner/products/domain/service_manual.entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'create_product.request.freezed.dart';
part 'create_product.request.g.dart';

/// Request DTO for creating a new product
///
/// Does not include ID as it will be generated by the server
@Freezed(toJson: true)
abstract class CreateProductRequest with _$CreateProductRequest {
  const factory CreateProductRequest({
    // General Information
    required String name,
    required String description,
    @Default('service') String productType,

    // Pricing & Inventory
    required double basePrice,
    double? salePrice,
    double? costPerItem,

    // Visibility
    @Default('draft') String status,
    @Default(true) bool onlineStore,

    // Organization
    required String category,
    @Default([]) List<String> tags,

    // Operations & Scheduling
    int? duration,
    int? buffer,
    int? capacity,

    @Default('any') String staffAllocation,
    @Default([]) List<String> staffIds,

    // Media
    @Default([]) List<String> images,

    // Facility Images
    @Default([]) List<FacilityImageEntity> facilityImages,

    // Reviews
    @Default([]) List<ReviewEntity> reviews,

    // Service Manual
    ServiceManualEntity? serviceManual,
  }) = _CreateProductRequest;

  factory CreateProductRequest.fromJson(Map<String, dynamic> json) =>
      _$CreateProductRequestFromJson(json);
}
