import 'package:freezed_annotation/freezed_annotation.dart';

part 'create_product.request.freezed.dart';
part 'create_product.request.g.dart';

/// Request DTO for creating a new product
///
/// Does not include ID as it will be generated by the server
@Freezed(toJson: true)
abstract class CreateProductRequest with _$CreateProductRequest {
  const factory CreateProductRequest({
    required String name,
    required double price,
    required String description,
    required String image,
    required String category,
  }) = _CreateProductRequest;

  factory CreateProductRequest.fromJson(Map<String, dynamic> json) =>
      _$CreateProductRequestFromJson(json);
}
