import { MigrationInterface, QueryRunner, TableUnique } from 'typeorm';

/**
 * Refactors the slug uniqueness constraint on the `products` table:
 *
 * BEFORE: Global unique index on (slug) — prevents different partners from
 *         creating a product with the same slug string.
 *
 * AFTER:  Composite unique constraint on (partner_id, slug) — uniqueness is
 *         scoped per-partner. Slugs are now auto-generated by the server as
 *         `{partner_brand}_{product_name}_{6-char-random}`, so collisions are
 *         extremely unlikely even within a single partner.
 */
export class RefactorProductSlugUniqueConstraint1778990000000
  implements MigrationInterface
{
  name = 'RefactorProductSlugUniqueConstraint1778990000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // 1. Drop the old global non-unique index on slug (if it exists)
    await queryRunner.query(`
      DROP INDEX IF EXISTS "IDX_PRODUCT_MERCHANT_SLUG";
    `);

    // 2. Drop the old auto-generated global unique constraint on slug (if any).
    //    TypeORM may have created this as "UQ_464f927ae360106b783ed0b4106".
    await queryRunner.query(`
      ALTER TABLE "products"
        DROP CONSTRAINT IF EXISTS "UQ_464f927ae360106b783ed0b4106";
    `);

    // 3. Also drop any other legacy unique constraint on slug alone.
    await queryRunner.query(`
      DO $$
      DECLARE
        c text;
      BEGIN
        FOR c IN
          SELECT constraint_name
          FROM information_schema.table_constraints
          WHERE table_name = 'products'
            AND constraint_type = 'UNIQUE'
            AND constraint_name NOT IN ('UQ_PRODUCT_PARTNER_SLUG')
            AND constraint_name IN (
              SELECT constraint_name
              FROM information_schema.constraint_column_usage
              WHERE table_name = 'products' AND column_name = 'slug'
            )
            AND (
              SELECT COUNT(*) FROM information_schema.constraint_column_usage
              WHERE table_name = 'products'
                AND constraint_name = c
            ) = 1
        LOOP
          EXECUTE format('ALTER TABLE products DROP CONSTRAINT IF EXISTS %I', c);
        END LOOP;
      END
      $$;
    `);

    // 4. Create the new composite unique constraint (partner_id, slug)
    await queryRunner.createUniqueConstraint(
      'products',
      new TableUnique({
        name: 'UQ_PRODUCT_PARTNER_SLUG',
        columnNames: ['partner_id', 'slug'],
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // 1. Drop the composite unique constraint
    await queryRunner.dropUniqueConstraint(
      'products',
      'UQ_PRODUCT_PARTNER_SLUG',
    );

    // 2. Restore the simple index on slug (non-unique, as it was before)
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_PRODUCT_MERCHANT_SLUG"
        ON "products" ("slug");
    `);
  }
}
