name: healytic_fe
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:

workspace:
 - user_app
 - admin_panel
 - common
