import 'package:admin_panel/features/common/widgets/analytics/analytics_async_panel.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_kpi_card.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_panel.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_period_filter.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_section_header.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_status_badge.widget.dart';
import 'package:admin_panel/features/partner/products/domain/product.entity.dart';
import 'package:admin_panel/features/partner/products/domain/product_analytics.entity.dart';
import 'package:admin_panel/features/partner/products/presentation/providers/product_analytics.provider.dart';
import 'package:common/utils/demensions.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

/// Analytics section used inside the product detail page.
class ProductDetailAnalyticsSection extends ConsumerWidget {
  const ProductDetailAnalyticsSection({super.key, required this.product});

  final Product product;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final analyticsAsync = ref.watch(
      productDetailAnalyticsProvider(product.id.value),
    );

    return analyticsAsync.when(
      data: (state) {
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AnalyticsSectionHeader(
              title: 'Performance Insights',
              subtitle:
                  'Service demand, review quality, and operational readiness '
                  'for this treatment.',
              icon: Icons.query_stats_rounded,
              trailing: AnalyticsPeriodFilter(
                selectedPeriod: state.selectedPeriod,
                onChanged: (period) {
                  ref
                      .read(
                        productDetailAnalyticsProvider(
                          product.id.value,
                        ).notifier,
                      )
                      .setTimePeriod(period);
                },
              ),
            ),
            if (state.isRefreshing) ...[
              AppDimens.verticalSmall,
              const LinearProgressIndicator(),
            ],
            AppDimens.verticalLarge,
            _ProductDetailKpiGrid(analytics: state.analytics),
            AppDimens.verticalLarge,
            _ProductDetailTopPanels(analytics: state.analytics),
            AppDimens.verticalLarge,
            _ProductReadinessPanel(analytics: state.analytics),
          ],
        );
      },
      loading: () =>
          const AnalyticsAsyncPanel.loading(title: 'Loading service analytics'),
      error: (error, _) => AnalyticsAsyncPanel.error(
        title: 'Unable to load service analytics',
        description: error.toString(),
        action: TextButton(
          onPressed: () {
            ref.invalidate(productDetailAnalyticsProvider(product.id.value));
          },
          child: const Text('Retry'),
        ),
      ),
    );
  }
}

class _ProductDetailKpiGrid extends StatelessWidget {
  const _ProductDetailKpiGrid({required this.analytics});

  final ProductDetailAnalytics analytics;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final crossAxisCount = constraints.maxWidth >= 1200
            ? 4
            : constraints.maxWidth >= 720
            ? 2
            : 1;

        return GridView.count(
          crossAxisCount: crossAxisCount,
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          crossAxisSpacing: AppDimens.spaceLg,
          mainAxisSpacing: AppDimens.spaceLg,
          childAspectRatio: 1.15,
          children: [
            AnalyticsKpiCard(
              label: 'Bookings',
              value: analytics.bookings.toString(),
              helper: 'Completed sessions in the selected period',
              icon: Icons.calendar_month_rounded,
              trend: analytics.bookingsDelta,
              trendPositive: true,
            ),
            AnalyticsKpiCard(
              label: 'Revenue',
              value: _currency(analytics.revenue),
              helper: 'Revenue generated by this service',
              icon: Icons.payments_rounded,
              trend: analytics.revenueDelta,
              trendPositive: true,
            ),
            AnalyticsKpiCard(
              label: 'Completion rate',
              value: '${analytics.completionRate.toStringAsFixed(1)}%',
              helper: 'Booking outcome quality for this service',
              icon: Icons.task_alt_rounded,
              trend: analytics.completionRateDelta,
              trendPositive: true,
            ),
            AnalyticsKpiCard(
              label: 'Average rating',
              value: '${analytics.averageRating.toStringAsFixed(1)}/5',
              helper: '${analytics.reviewCount} submitted reviews',
              icon: Icons.star_rounded,
              trend: 1.6,
              trendPositive: true,
              badgeLabel: 'Reviews',
              badgeTone: AnalyticsStatusTone.warning,
            ),
          ],
        );
      },
    );
  }
}

class _ProductDetailTopPanels extends StatelessWidget {
  const _ProductDetailTopPanels({required this.analytics});

  final ProductDetailAnalytics analytics;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final isWide = constraints.maxWidth >= 1100;

        if (!isWide) {
          return Column(
            children: [
              _DetailTrendPanel(points: analytics.trendPoints),
              AppDimens.verticalLarge,
              _ReviewQualityPanel(analytics: analytics),
            ],
          );
        }

        return Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(
              flex: 3,
              child: _DetailTrendPanel(points: analytics.trendPoints),
            ),
            AppDimens.horizontalLarge,
            Expanded(flex: 2, child: _ReviewQualityPanel(analytics: analytics)),
          ],
        );
      },
    );
  }
}

class _DetailTrendPanel extends StatelessWidget {
  const _DetailTrendPanel({required this.points});

  final List<ProductTrendPoint> points;

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    final theme = Theme.of(context);

    return AnalyticsPanel(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const AnalyticsSectionHeader(
            title: 'Demand trend',
            subtitle: 'Track service bookings and revenue momentum.',
            icon: Icons.multiline_chart_rounded,
          ),
          AppDimens.verticalLarge,
          SizedBox(
            height: 240,
            child: LineChart(
              LineChartData(
                borderData: FlBorderData(show: false),
                gridData: FlGridData(
                  show: true,
                  drawVerticalLine: false,
                  getDrawingHorizontalLine: (_) =>
                      FlLine(color: colorScheme.outlineVariant, strokeWidth: 1),
                ),
                titlesData: FlTitlesData(
                  topTitles: const AxisTitles(
                    sideTitles: SideTitles(showTitles: false),
                  ),
                  rightTitles: const AxisTitles(
                    sideTitles: SideTitles(showTitles: false),
                  ),
                  leftTitles: const AxisTitles(
                    sideTitles: SideTitles(showTitles: false),
                  ),
                  bottomTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: true,
                      getTitlesWidget: (value, meta) {
                        final index = value.toInt();
                        if (index < 0 || index >= points.length) {
                          return const SizedBox.shrink();
                        }
                        return Text(
                          points[index].label,
                          style: theme.textTheme.labelMedium?.copyWith(
                            color: colorScheme.onSurfaceVariant,
                          ),
                        );
                      },
                    ),
                  ),
                ),
                minX: 0,
                maxX: (points.length - 1).toDouble(),
                lineBarsData: [
                  LineChartBarData(
                    spots: [
                      for (var i = 0; i < points.length; i++)
                        FlSpot(i.toDouble(), points[i].bookings),
                    ],
                    isCurved: true,
                    color: colorScheme.primary,
                    barWidth: 3,
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _ReviewQualityPanel extends StatelessWidget {
  const _ReviewQualityPanel({required this.analytics});

  final ProductDetailAnalytics analytics;

  @override
  Widget build(BuildContext context) {
    return AnalyticsPanel(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const AnalyticsSectionHeader(
            title: 'Review quality',
            subtitle: 'Distribution of sentiment across submitted reviews.',
            icon: Icons.reviews_rounded,
          ),
          AppDimens.verticalLarge,
          for (final bucket in analytics.reviewDistribution) ...[
            _ReviewRow(bucket: bucket, total: analytics.reviewCount),
            AppDimens.verticalMediumSmall,
          ],
          if (analytics.alerts.isNotEmpty) ...[
            AppDimens.verticalMedium,
            for (final alert in analytics.alerts) ...[
              AnalyticsStatusBadge(label: alert.title, tone: alert.tone),
              AppDimens.verticalExtraSmall,
              Text(alert.detail),
              AppDimens.verticalMedium,
            ],
          ],
        ],
      ),
    );
  }
}

class _ProductReadinessPanel extends StatelessWidget {
  const _ProductReadinessPanel({required this.analytics});

  final ProductDetailAnalytics analytics;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final isWide = constraints.maxWidth >= 1100;

        if (!isWide) {
          return Column(
            children: [
              _OperationalMetricsPanel(metrics: analytics.operationalMetrics),
              AppDimens.verticalLarge,
              _PeerRankingPanel(items: analytics.peerRanking),
            ],
          );
        }

        return Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(
              flex: 3,
              child: _OperationalMetricsPanel(
                metrics: analytics.operationalMetrics,
              ),
            ),
            AppDimens.horizontalLarge,
            Expanded(
              flex: 2,
              child: _PeerRankingPanel(items: analytics.peerRanking),
            ),
          ],
        );
      },
    );
  }
}

class _OperationalMetricsPanel extends StatelessWidget {
  const _OperationalMetricsPanel({required this.metrics});

  final List<ProductOperationalMetric> metrics;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return AnalyticsPanel(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const AnalyticsSectionHeader(
            title: 'Operational readiness',
            subtitle: 'Visibility, staffing, scheduling, and content signals.',
            icon: Icons.settings_suggest_rounded,
          ),
          AppDimens.verticalLarge,
          LayoutBuilder(
            builder: (context, constraints) {
              final crossAxisCount = constraints.maxWidth >= 800 ? 2 : 1;

              return GridView.count(
                crossAxisCount: crossAxisCount,
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                crossAxisSpacing: AppDimens.spaceLg,
                mainAxisSpacing: AppDimens.spaceLg,
                childAspectRatio: 2.15,
                children: [
                  for (final metric in metrics)
                    Container(
                      padding: AppDimens.paddingAllMedium,
                      decoration: BoxDecoration(
                        color: colorScheme.surfaceContainerHighest.withValues(
                          alpha: 0.2,
                        ),
                        borderRadius: AppDimens.radiusMedium,
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          AnalyticsStatusBadge(
                            label: metric.label,
                            tone: metric.tone,
                          ),
                          AppDimens.verticalMediumSmall,
                          Text(
                            metric.value,
                            style: theme.textTheme.titleLarge?.copyWith(
                              fontWeight: AppDimens.fontWeightBold,
                            ),
                          ),
                          AppDimens.verticalExtraSmall,
                          Text(
                            metric.detail,
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: colorScheme.onSurfaceVariant,
                            ),
                          ),
                        ],
                      ),
                    ),
                ],
              );
            },
          ),
        ],
      ),
    );
  }
}

class _PeerRankingPanel extends StatelessWidget {
  const _PeerRankingPanel({required this.items});

  final List<ProductServicePerformance> items;

  @override
  Widget build(BuildContext context) {
    return AnalyticsPanel(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const AnalyticsSectionHeader(
            title: 'Peer comparison',
            subtitle: 'Position this service against the strongest peers.',
            icon: Icons.compare_arrows_rounded,
          ),
          AppDimens.verticalLarge,
          for (final item in items) ...[
            _PeerRankingRow(item: item),
            AppDimens.verticalMediumSmall,
          ],
        ],
      ),
    );
  }
}

class _PeerRankingRow extends StatelessWidget {
  const _PeerRankingRow({required this.item});

  final ProductServicePerformance item;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                item.name,
                style: theme.textTheme.titleSmall?.copyWith(
                  fontWeight: AppDimens.fontWeightBold,
                ),
              ),
              AppDimens.verticalExtraSmall,
              Text(
                '${item.bookings} bookings • ${item.averageRating}/5',
                style: theme.textTheme.bodySmall?.copyWith(
                  color: colorScheme.onSurfaceVariant,
                ),
              ),
            ],
          ),
        ),
        Text(_currency(item.revenue)),
      ],
    );
  }
}

class _ReviewRow extends StatelessWidget {
  const _ReviewRow({required this.bucket, required this.total});

  final ProductReviewBucket bucket;
  final int total;

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    final ratio = total == 0 ? 0.0 : bucket.count / total;

    return Row(
      children: [
        SizedBox(width: 32, child: Text('${bucket.stars}★')),
        Expanded(
          child: ClipRRect(
            borderRadius: AppDimens.radiusPill,
            child: LinearProgressIndicator(
              value: ratio,
              minHeight: AppDimens.spaceMd,
              backgroundColor: colorScheme.surfaceContainerHighest,
            ),
          ),
        ),
        AppDimens.horizontalMedium,
        SizedBox(
          width: 40,
          child: Text(bucket.count.toString(), textAlign: TextAlign.end),
        ),
      ],
    );
  }
}

String _currency(double value) {
  final compact = value >= 1000000
      ? '${(value / 1000000).toStringAsFixed(1)}M'
      : '${(value / 1000).toStringAsFixed(0)}K';
  return '$compact₫';
}
