import 'package:admin_panel/features/common/widgets/analytics/analytics_async_panel.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_kpi_card.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_panel.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_period_filter.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_section_header.widget.dart';
import 'package:admin_panel/features/common/widgets/analytics/analytics_status_badge.widget.dart';
import 'package:admin_panel/features/partner/products/domain/product_analytics.entity.dart';
import 'package:admin_panel/features/partner/products/presentation/providers/product_analytics.provider.dart';
import 'package:common/utils/demensions.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

/// Analytics overview for the product index page.
class ProductOverviewAnalyticsSection extends ConsumerWidget {
  const ProductOverviewAnalyticsSection({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final analyticsAsync = ref.watch(productOverviewAnalyticsProvider);

    return analyticsAsync.when(
      data: (state) {
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AnalyticsSectionHeader(
              title: 'Service Performance',
              subtitle:
                  'Finance-style KPIs with booking, review, and catalog '
                  'health visibility.',
              icon: Icons.insights_rounded,
              trailing: AnalyticsPeriodFilter(
                selectedPeriod: state.selectedPeriod,
                onChanged: (period) {
                  ref
                      .read(productOverviewAnalyticsProvider.notifier)
                      .setTimePeriod(period);
                },
              ),
            ),
            if (state.isRefreshing) ...[
              AppDimens.verticalSmall,
              const LinearProgressIndicator(),
            ],
            AppDimens.verticalLarge,
            _ProductOverviewKpiGrid(analytics: state.analytics),
            AppDimens.verticalLarge,
            _ProductOverviewTopPanels(analytics: state.analytics),
            AppDimens.verticalLarge,
            _ProductBookingMetricsPanel(analytics: state.analytics),
          ],
        );
      },
      loading: () =>
          const AnalyticsAsyncPanel.loading(title: 'Loading product analytics'),
      error: (error, _) => AnalyticsAsyncPanel.error(
        title: 'Unable to load product analytics',
        description: error.toString(),
        action: TextButton(
          onPressed: () {
            ref.invalidate(productOverviewAnalyticsProvider);
          },
          child: const Text('Retry'),
        ),
      ),
    );
  }
}

class _ProductOverviewKpiGrid extends StatelessWidget {
  const _ProductOverviewKpiGrid({required this.analytics});

  final ProductOverviewAnalytics analytics;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final childAspectRatio = constraints.maxWidth >= 700 ? 1.15 : 0.95;

        return GridView.extent(
          maxCrossAxisExtent: 300,
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          crossAxisSpacing: AppDimens.spaceLg,
          mainAxisSpacing: AppDimens.spaceLg,
          childAspectRatio: childAspectRatio,
          children: [
            AnalyticsKpiCard(
              label: 'Active services',
              value: '${analytics.activeProducts}/${analytics.totalProducts}',
              helper:
                  '${analytics.totalProducts - analytics.activeProducts} '
                  'services still need activation',
              icon: Icons.medical_services_rounded,
              trend: 2.4,
              trendPositive: true,
              badgeLabel: 'Catalog',
            ),
            AnalyticsKpiCard(
              label: 'Bookings',
              value: analytics.bookings.toString(),
              helper: 'Estimated completed bookings in the selected period',
              icon: Icons.calendar_month_rounded,
              trend: analytics.bookingsDelta,
              trendPositive: true,
              badgeLabel: 'Demand',
              badgeTone: AnalyticsStatusTone.positive,
            ),
            AnalyticsKpiCard(
              label: 'Revenue',
              value: _currency(analytics.revenue),
              helper: 'Revenue generated by visible services',
              icon: Icons.payments_rounded,
              trend: analytics.revenueDelta,
              trendPositive: true,
              badgeLabel: 'Finance',
            ),
            AnalyticsKpiCard(
              label: 'Average rating',
              value: '${analytics.averageRating.toStringAsFixed(1)}/5',
              helper: '${analytics.reviewCount} reviews across the catalog',
              icon: Icons.star_rounded,
              trend: analytics.ratingDelta,
              trendPositive: true,
              badgeLabel: 'Reputation',
              badgeTone: AnalyticsStatusTone.warning,
            ),
          ],
        );
      },
    );
  }
}

class _ProductOverviewTopPanels extends StatelessWidget {
  const _ProductOverviewTopPanels({required this.analytics});

  final ProductOverviewAnalytics analytics;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _ProductTrendPanel(points: analytics.trendPoints),
        AppDimens.verticalLarge,
        _ProductRankingPanel(
          items: analytics.topServices,
          categories: analytics.categoryPerformance,
        ),
      ],
    );
  }
}

class _ProductTrendPanel extends StatelessWidget {
  const _ProductTrendPanel({required this.points});

  final List<ProductTrendPoint> points;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    if (points.isEmpty) {
      return const AnalyticsAsyncPanel.empty(
        title: 'No booking trend data',
        description:
            'Trend lines will appear when services '
            'accumulate demand.',
      );
    }

    final maxY = points.fold<double>(
      0,
      (maxValue, point) =>
          point.revenue / 1000 > maxValue ? point.revenue / 1000 : maxValue,
    );

    return AnalyticsPanel(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const AnalyticsSectionHeader(
            title: 'Booking and revenue trend',
            subtitle:
                'Bookings and revenue move together '
                'across the period.',
            icon: Icons.show_chart_rounded,
          ),
          AppDimens.verticalMedium,
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: const [
              _LegendChip(
                color: Colors.transparent,
                label: 'Bookings',
                icon: Icons.trending_up_rounded,
              ),
              _LegendChip(
                color: Colors.transparent,
                label: 'Revenue (K VND)',
                icon: Icons.payments_outlined,
              ),
            ],
          ),
          AppDimens.verticalMedium,
          AspectRatio(
            aspectRatio: 2.2,
            child: LineChart(
              LineChartData(
                lineTouchData: LineTouchData(
                  enabled: true,
                  handleBuiltInTouches: true,
                  touchSpotThreshold: 20,
                  getTouchedSpotIndicator: (barData, spotIndexes) {
                    return spotIndexes.map((_) {
                      return TouchedSpotIndicatorData(
                        const FlLine(color: Colors.transparent),
                        FlDotData(
                          show: true,
                          getDotPainter: (spot, percent, barData, index) {
                            return FlDotCirclePainter(
                              radius: 6,
                              color: colorScheme.surface,
                              strokeWidth: 2,
                              strokeColor:
                                  barData.color ?? colorScheme.secondary,
                            );
                          },
                        ),
                      );
                    }).toList();
                  },
                  touchTooltipData: LineTouchTooltipData(
                    fitInsideHorizontally: true,
                    fitInsideVertically: true,
                    getTooltipColor: (_) => colorScheme.surface,
                    tooltipBorder: BorderSide(
                      color: colorScheme.outlineVariant,
                    ),
                    getTooltipItems: (touchedSpots) {
                      return touchedSpots.map((touchedSpot) {
                        final textStyle = theme.textTheme.labelMedium?.copyWith(
                          color: touchedSpot.bar.color,
                          fontWeight: AppDimens.fontWeightBold,
                        );
                        if (touchedSpot.barIndex == 0) {
                          return LineTooltipItem(
                            '${touchedSpot.y.toInt()}'
                            ' Bookings',
                            textStyle ?? const TextStyle(),
                          );
                        }
                        return LineTooltipItem(
                          _currency(touchedSpot.y * 1000),
                          textStyle ?? const TextStyle(),
                        );
                      }).toList();
                    },
                  ),
                ),
                minX: 0,
                maxX: (points.length - 1).toDouble(),
                minY: 0,
                maxY: maxY * 1.25,
                clipData: const FlClipData.all(),
                gridData: FlGridData(
                  show: true,
                  drawVerticalLine: false,
                  getDrawingHorizontalLine: (_) => FlLine(
                    color: colorScheme.outlineVariant,
                    strokeWidth: 1,
                    dashArray: const [4, 4],
                  ),
                ),
                borderData: FlBorderData(show: false),
                titlesData: FlTitlesData(
                  topTitles: const AxisTitles(
                    sideTitles: SideTitles(showTitles: false),
                  ),
                  rightTitles: const AxisTitles(
                    sideTitles: SideTitles(showTitles: false),
                  ),
                  leftTitles: const AxisTitles(
                    sideTitles: SideTitles(showTitles: false),
                  ),
                  bottomTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: true,
                      reservedSize: 32,
                      interval: 1,
                      getTitlesWidget: (value, meta) {
                        final index = value.toInt();
                        if (!_shouldShowTrendAxisLabel(
                          value: value,
                          index: index,
                          points: points,
                        )) {
                          return const SizedBox.shrink();
                        }
                        return Padding(
                          padding: AppDimens.paddingTopSmall,
                          child: Text(
                            points[index].label,
                            style: theme.textTheme.labelMedium?.copyWith(
                              color: colorScheme.onSurfaceVariant,
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                ),
                lineBarsData: [
                  LineChartBarData(
                    spots: [
                      for (var i = 0; i < points.length; i++)
                        FlSpot(i.toDouble(), points[i].bookings),
                    ],
                    isCurved: true,
                    preventCurveOverShooting: true,
                    barWidth: 3,
                    color: colorScheme.primary,
                    dotData: FlDotData(
                      show: true,
                      getDotPainter: (_, __, ___, ____) {
                        return FlDotCirclePainter(
                          radius: 4,
                          color: colorScheme.surface,
                          strokeWidth: 2,
                          strokeColor: colorScheme.primary,
                        );
                      },
                    ),
                  ),
                  LineChartBarData(
                    spots: [
                      for (var i = 0; i < points.length; i++)
                        FlSpot(i.toDouble(), points[i].revenue / 1000),
                    ],
                    isCurved: true,
                    preventCurveOverShooting: true,
                    barWidth: 3,
                    color: colorScheme.tertiary,
                    dotData: FlDotData(
                      show: true,
                      getDotPainter: (_, __, ___, ____) {
                        return FlDotCirclePainter(
                          radius: 4,
                          color: colorScheme.surface,
                          strokeWidth: 2,
                          strokeColor: colorScheme.tertiary,
                        );
                      },
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

bool _shouldShowTrendAxisLabel({
  required double value,
  required int index,
  required List<ProductTrendPoint> points,
}) {
  if (value != index.toDouble() || index < 0 || index >= points.length) {
    return false;
  }
  return index == 0 || points[index].label != points[index - 1].label;
}

class _ProductRankingPanel extends StatelessWidget {
  const _ProductRankingPanel({required this.items, required this.categories});

  final List<ProductServicePerformance> items;
  final List<ProductCategoryPerformance> categories;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return AnalyticsPanel(
      child: LayoutBuilder(
        builder: (context, constraints) {
          final useSideBySide = constraints.maxWidth >= 980;
          final sections = [
            _RankingSectionBlock(
              title: 'Top services',
              child: _TopServicesGrid(items: items),
            ),
            _RankingSectionBlock(
              title: 'Category strength',
              child: _CategoryStrengthGrid(categories: categories),
            ),
          ];

          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const AnalyticsSectionHeader(
                title: 'Category and service leaders',
                subtitle:
                    'See which categories and hero services drive demand.',
                icon: Icons.leaderboard_rounded,
              ),
              AppDimens.verticalLarge,
              if (useSideBySide)
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(flex: 3, child: sections.first),
                    AppDimens.horizontalLarge,
                    Expanded(flex: 2, child: sections.last),
                  ],
                )
              else ...[
                sections.first,
                Padding(
                  padding: AppDimens.paddingVerticalMedium,
                  child: Divider(color: colorScheme.outlineVariant),
                ),
                sections.last,
              ],
            ],
          );
        },
      ),
    );
  }
}

class _RankingSectionBlock extends StatelessWidget {
  const _RankingSectionBlock({required this.title, required this.child});

  final String title;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: theme.textTheme.titleMedium?.copyWith(
            fontWeight: AppDimens.fontWeightBold,
          ),
        ),
        AppDimens.verticalMedium,
        child,
      ],
    );
  }
}

class _ProductBookingMetricsPanel extends StatelessWidget {
  const _ProductBookingMetricsPanel({required this.analytics});

  final ProductOverviewAnalytics analytics;

  @override
  Widget build(BuildContext context) {
    final bookingMetrics = analytics.bookingMetrics;
    final items = [
      _BookingMetricItem(
        label: 'Total bookings',
        value: bookingMetrics.totalBookings.toString(),
        helper: 'Across the selected period',
        tone: AnalyticsStatusTone.neutral,
      ),
      _BookingMetricItem(
        label: 'Delayed',
        value: bookingMetrics.delayedBookings.toString(),
        helper: 'Over ${bookingMetrics.delayThresholdMinutes} min',
        tone: AnalyticsStatusTone.critical,
      ),
      _BookingMetricItem(
        label: 'Pending',
        value: bookingMetrics.pendingBookings.toString(),
        helper: 'Waiting for confirmation',
        tone: AnalyticsStatusTone.warning,
      ),
      _BookingMetricItem(
        label: 'Completed',
        value: bookingMetrics.completedBookings.toString(),
        helper: 'Finished successfully',
        tone: AnalyticsStatusTone.positive,
      ),
    ];
    final statusBreakdown = normalizeProductBookingStatusMetrics(
      bookingMetrics.statusBreakdown,
    );

    return AnalyticsPanel(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const AnalyticsSectionHeader(
            title: 'Booking operations',
            subtitle:
                'Track booking flow, delays, and status distribution for the '
                'selected period.',
            icon: Icons.event_note_rounded,
          ),
          AppDimens.verticalLarge,
          _BookingOperationsLayout(
            summary: items.first,
            operations: items.skip(1).toList(),
            statusBreakdown: statusBreakdown,
            alerts: bookingMetrics.alerts,
          ),
        ],
      ),
    );
  }
}

class _BookingOperationsLayout extends StatelessWidget {
  const _BookingOperationsLayout({
    required this.summary,
    required this.operations,
    required this.statusBreakdown,
    required this.alerts,
  });

  final _BookingMetricItem summary;
  final List<_BookingMetricItem> operations;
  final List<ProductBookingStatusMetric> statusBreakdown;
  final List<ProductAnalyticsAlert> alerts;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final isWide = constraints.maxWidth >= 1040;
        final summaryColumn = _BookingSummaryColumn(
          summary: summary,
          alerts: alerts,
        );
        final detailsColumn = _BookingDetailsColumn(
          operations: operations,
          statusBreakdown: statusBreakdown,
        );

        if (!isWide) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [summaryColumn, AppDimens.verticalLarge, detailsColumn],
          );
        }

        return Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(flex: 3, child: summaryColumn),
            AppDimens.horizontalLarge,
            Expanded(flex: 5, child: detailsColumn),
          ],
        );
      },
    );
  }
}

class _BookingSummaryColumn extends StatelessWidget {
  const _BookingSummaryColumn({required this.summary, required this.alerts});

  final _BookingMetricItem summary;
  final List<ProductAnalyticsAlert> alerts;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _BookingSummaryTile(item: summary),
        if (alerts.isNotEmpty) ...[
          AppDimens.verticalMedium,
          for (final alert in alerts) ...[
            _AlertTile(
              title: alert.title,
              detail: alert.detail,
              tone: alert.tone,
            ),
            AppDimens.verticalMediumSmall,
          ],
        ],
      ],
    );
  }
}

class _BookingDetailsColumn extends StatelessWidget {
  const _BookingDetailsColumn({
    required this.operations,
    required this.statusBreakdown,
  });

  final List<_BookingMetricItem> operations;
  final List<ProductBookingStatusMetric> statusBreakdown;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _BookingMetricGrid(items: operations),
        if (statusBreakdown.isNotEmpty) ...[
          AppDimens.verticalLarge,
          Text(
            'Booking status',
            style: Theme.of(context).textTheme.titleMedium?.copyWith(
              fontWeight: AppDimens.fontWeightBold,
            ),
          ),
          AppDimens.verticalMedium,
          _BookingStatusStrip(items: statusBreakdown),
        ],
      ],
    );
  }
}

class _BookingMetricGrid extends StatelessWidget {
  const _BookingMetricGrid({required this.items});

  final List<_BookingMetricItem> items;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final childAspectRatio = constraints.maxWidth >= 820
            ? 1.35
            : constraints.maxWidth >= 560
            ? 1.25
            : 1.05;

        return GridView.extent(
          maxCrossAxisExtent: 240,
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          crossAxisSpacing: AppDimens.spaceLg,
          mainAxisSpacing: AppDimens.spaceLg,
          childAspectRatio: childAspectRatio,
          children: [for (final item in items) _BookingMetricTile(item: item)],
        );
      },
    );
  }
}

class _BookingSummaryTile extends StatelessWidget {
  const _BookingSummaryTile({required this.item});

  final _BookingMetricItem item;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Container(
      padding: AppDimens.paddingAllLarge,
      decoration: BoxDecoration(
        color: colorScheme.primaryContainer.withValues(alpha: 0.18),
        borderRadius: AppDimens.radiusMedium,
        border: Border.all(color: colorScheme.primary.withValues(alpha: 0.22)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          AnalyticsStatusBadge(label: item.label, tone: item.tone),
          AppDimens.verticalMedium,
          Text(
            item.value,
            style: theme.textTheme.displaySmall?.copyWith(
              fontWeight: AppDimens.fontWeightBold,
            ),
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
          AppDimens.verticalExtraSmall,
          Text(
            item.helper,
            style: theme.textTheme.bodyMedium?.copyWith(
              color: colorScheme.onSurfaceVariant,
            ),
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
          ),
        ],
      ),
    );
  }
}

class _BookingMetricTile extends StatelessWidget {
  const _BookingMetricTile({required this.item});

  final _BookingMetricItem item;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Container(
      padding: AppDimens.paddingAllMediumSmall,
      decoration: BoxDecoration(
        color: colorScheme.surfaceContainerHighest.withValues(alpha: 0.25),
        borderRadius: AppDimens.radiusMedium,
      ),
      child: LayoutBuilder(
        builder: (context, constraints) {
          final isCompact = constraints.maxHeight < 128;

          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: [
              AnalyticsStatusBadge(label: item.label, tone: item.tone),
              AppDimens.verticalSmall,
              Text(
                item.value,
                style:
                    (isCompact
                            ? theme.textTheme.headlineSmall
                            : theme.textTheme.displaySmall)
                        ?.copyWith(fontWeight: AppDimens.fontWeightBold),
              ),
              AppDimens.verticalExtraSmall,
              Text(
                item.helper,
                style:
                    (isCompact
                            ? theme.textTheme.bodySmall
                            : theme.textTheme.bodyMedium)
                        ?.copyWith(color: colorScheme.onSurfaceVariant),
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
              ),
            ],
          );
        },
      ),
    );
  }
}

class _BookingStatusStrip extends StatelessWidget {
  const _BookingStatusStrip({required this.items});

  final List<ProductBookingStatusMetric> items;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final spacing = AppDimens.spaceMd;
        final columns = constraints.maxWidth >= 980
            ? 4
            : constraints.maxWidth >= 620
            ? 2
            : 1;
        final itemWidth =
            (constraints.maxWidth - (spacing * (columns - 1))) / columns;

        return Wrap(
          spacing: spacing,
          runSpacing: spacing,
          children: [
            for (final item in items)
              SizedBox(
                width: itemWidth,
                child: _BookingStatusTile(item: item),
              ),
          ],
        );
      },
    );
  }
}

class _BookingStatusTile extends StatelessWidget {
  const _BookingStatusTile({required this.item});

  final ProductBookingStatusMetric item;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Container(
      padding: AppDimens.paddingAllMedium,
      decoration: BoxDecoration(
        color: colorScheme.surfaceContainerHighest.withValues(alpha: 0.18),
        borderRadius: AppDimens.radiusMedium,
        border: Border.all(color: colorScheme.outlineVariant),
      ),
      child: Row(
        children: [
          Expanded(
            child: AnalyticsStatusBadge(label: item.label, tone: item.tone),
          ),
          AppDimens.horizontalMedium,
          Text(
            item.count.toString(),
            style: theme.textTheme.titleLarge?.copyWith(
              fontWeight: AppDimens.fontWeightBold,
            ),
          ),
        ],
      ),
    );
  }
}

class _AlertTile extends StatelessWidget {
  const _AlertTile({
    required this.title,
    required this.detail,
    required this.tone,
  });

  final String title;
  final String detail;
  final AnalyticsStatusTone tone;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return LayoutBuilder(
      builder: (context, constraints) {
        final shouldStack = constraints.maxWidth < 520;
        final detailText = Text(
          detail,
          style: theme.textTheme.bodyMedium?.copyWith(
            color: colorScheme.onSurfaceVariant,
          ),
        );

        return Container(
          padding: AppDimens.paddingAllMedium,
          decoration: BoxDecoration(
            borderRadius: AppDimens.radiusMedium,
            border: Border.all(color: colorScheme.outlineVariant),
          ),
          child: shouldStack
              ? Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    AnalyticsStatusBadge(label: title, tone: tone),
                    AppDimens.verticalSmall,
                    detailText,
                  ],
                )
              : Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    AnalyticsStatusBadge(label: title, tone: tone),
                    AppDimens.horizontalMedium,
                    Expanded(child: detailText),
                  ],
                ),
        );
      },
    );
  }
}

class _RankingSpotlightGrid extends StatelessWidget {
  const _RankingSpotlightGrid({super.key, required this.children});

  final List<Widget> children;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final isTwoColumn = constraints.maxWidth >= 700;
        final spacing = AppDimens.spaceMd;
        final itemWidth = isTwoColumn
            ? (constraints.maxWidth - spacing) / 2
            : constraints.maxWidth;

        return Wrap(
          spacing: spacing,
          runSpacing: spacing,
          children: [
            for (final child in children)
              SizedBox(width: itemWidth, child: child),
          ],
        );
      },
    );
  }
}

class _TopServicesGrid extends StatelessWidget {
  const _TopServicesGrid({required this.items});

  final List<ProductServicePerformance> items;

  @override
  Widget build(BuildContext context) {
    final topServices = items.take(3).toList(growable: false);

    return _RankingSpotlightGrid(
      key: const ValueKey('top-services-grid'),
      children: [
        for (var index = 0; index < topServices.length; index++)
          _RankingSpotlightCard(
            rank: index + 1,
            title: topServices[index].name,
            subtitle: topServices[index].categoryName,
            revenue: _currency(topServices[index].revenue),
            primaryMetric: _RankingMetricData(
              icon: Icons.calendar_month_rounded,
              label: '${topServices[index].bookings} bookings',
            ),
            secondaryMetric: _RankingMetricData(
              icon: Icons.star_rounded,
              label: '${topServices[index].averageRating}/5',
            ),
          ),
      ],
    );
  }
}

class _CategoryStrengthGrid extends StatelessWidget {
  const _CategoryStrengthGrid({required this.categories});

  final List<ProductCategoryPerformance> categories;

  @override
  Widget build(BuildContext context) {
    final topCategories = categories.take(2).toList(growable: false);

    return _RankingSpotlightGrid(
      key: const ValueKey('category-strength-grid'),
      children: [
        for (var index = 0; index < topCategories.length; index++)
          _RankingSpotlightCard(
            rank: index + 1,
            title: topCategories[index].categoryName,
            subtitle: 'Category leader',
            revenue: _currency(topCategories[index].revenue),
            primaryMetric: _RankingMetricData(
              icon: Icons.calendar_month_rounded,
              label: '${topCategories[index].bookings} bookings',
            ),
            secondaryMetric: _RankingMetricData(
              icon: Icons.star_rounded,
              label:
                  '${topCategories[index].averageRating.toStringAsFixed(1)}/5 avg rating',
            ),
          ),
      ],
    );
  }
}

class _RankingSpotlightCard extends StatelessWidget {
  const _RankingSpotlightCard({
    required this.rank,
    required this.title,
    required this.subtitle,
    required this.revenue,
    required this.primaryMetric,
    required this.secondaryMetric,
  });

  final int rank;
  final String title;
  final String subtitle;
  final String revenue;
  final _RankingMetricData primaryMetric;
  final _RankingMetricData secondaryMetric;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return DecoratedBox(
      decoration: BoxDecoration(
        color: colorScheme.surface,
        borderRadius: AppDimens.radiusMedium,
        border: Border.all(
          color: colorScheme.outlineVariant.withValues(alpha: 0.55),
        ),
      ),
      child: Padding(
        padding: AppDimens.paddingAllMedium,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                DecoratedBox(
                  decoration: BoxDecoration(
                    color: colorScheme.surfaceContainerHighest.withValues(
                      alpha: 0.5,
                    ),
                    borderRadius: AppDimens.radiusPill,
                  ),
                  child: Padding(
                    padding: AppDimens.paddingHorizontalSmall.add(
                      AppDimens.paddingVerticalExtraSmall,
                    ),
                    child: Text(
                      '#$rank',
                      style: theme.textTheme.labelMedium?.copyWith(
                        color: colorScheme.onSurfaceVariant,
                        fontWeight: AppDimens.fontWeightSemiBold,
                      ),
                    ),
                  ),
                ),
                AppDimens.horizontalMedium,
                Expanded(
                  child: Text(
                    revenue,
                    textAlign: TextAlign.end,
                    style: theme.textTheme.titleLarge?.copyWith(
                      fontWeight: AppDimens.fontWeightBold,
                    ),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
            AppDimens.verticalMedium,
            Text(
              title,
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: AppDimens.fontWeightBold,
              ),
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
            ),
            AppDimens.verticalExtraSmall,
            Text(
              subtitle,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: colorScheme.onSurfaceVariant,
              ),
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
            AppDimens.verticalMedium,
            Wrap(
              spacing: AppDimens.spaceSm,
              runSpacing: AppDimens.spaceSm,
              children: [
                _RankingMetricChip(data: primaryMetric),
                _RankingMetricChip(data: secondaryMetric),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _RankingMetricChip extends StatelessWidget {
  const _RankingMetricChip({required this.data});

  final _RankingMetricData data;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return DecoratedBox(
      decoration: BoxDecoration(
        color: colorScheme.surfaceContainerHighest.withValues(alpha: 0.35),
        borderRadius: AppDimens.radiusPill,
      ),
      child: Padding(
        padding: AppDimens.paddingHorizontalSmall.add(
          AppDimens.paddingVerticalExtraSmall,
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              data.icon,
              size: AppDimens.iconSm,
              color: colorScheme.onSurfaceVariant,
            ),
            AppDimens.horizontalExtraSmall,
            Text(
              data.label,
              style: theme.textTheme.labelMedium?.copyWith(
                color: colorScheme.onSurfaceVariant,
                fontWeight: AppDimens.fontWeightSemiBold,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _RankingMetricData {
  const _RankingMetricData({required this.icon, required this.label});

  final IconData icon;
  final String label;
}

class _LegendChip extends StatelessWidget {
  const _LegendChip({
    required this.color,
    required this.label,
    required this.icon,
  });

  final Color color;
  final String label;
  final IconData icon;

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return Container(
      padding: AppDimens.paddingHorizontalSmall.add(
        AppDimens.paddingVerticalExtraSmall,
      ),
      decoration: BoxDecoration(
        color: colorScheme.surfaceContainerHighest.withValues(alpha: 0.4),
        borderRadius: AppDimens.radiusPill,
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: AppDimens.iconSm, color: colorScheme.primary),
          AppDimens.horizontalExtraSmall,
          Text(label),
        ],
      ),
    );
  }
}

class _BookingMetricItem {
  const _BookingMetricItem({
    required this.label,
    required this.value,
    required this.helper,
    required this.tone,
  });

  final String label;
  final String value;
  final String helper;
  final AnalyticsStatusTone tone;
}

List<ProductBookingStatusMetric> normalizeProductBookingStatusMetrics(
  List<ProductBookingStatusMetric> items,
) {
  const supportedOrder = <String, int>{
    'confirmed': 0,
    'cancelled': 1,
    'no_show': 2,
    'rescheduled': 3,
  };

  final filtered = items
      .where(
        (item) => supportedOrder.containsKey(item.statusKey) && item.count > 0,
      )
      .toList();

  filtered.sort(
    (left, right) => supportedOrder[left.statusKey]!.compareTo(
      supportedOrder[right.statusKey]!,
    ),
  );

  return filtered;
}

String _currency(double value) {
  final compact = value >= 1000000
      ? '${(value / 1000000).toStringAsFixed(1)}M'
      : '${(value / 1000).toStringAsFixed(0)}K';
  return '$compact₫';
}
