export const CART_ERROR_CODES = {
  INVALID_SERVICE: 'INVALID_SERVICE',
  ITEM_ALREADY_EXISTS: 'ITEM_ALREADY_EXISTS',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  INVALID_COUPON: 'INVALID_COUPON',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_LIMIT_REACHED: 'COUPON_LIMIT_REACHED',
  COUPON_NOT_APPLICABLE: 'COUPON_NOT_APPLICABLE',
} as const;

export const POSTGRES_UNIQUE_VIOLATION = '23505';
