export const CART_ERROR_CODES = {
  INVALID_SERVICE: 'INVALID_SERVICE',
  INVALID_EMPLOYEE: 'INVALID_EMPLOYEE',
  EMPLOYEE_NOT_ELIGIBLE: 'EMPLOYEE_NOT_ELIGIBLE',
  ITEM_ALREADY_EXISTS: 'ITEM_ALREADY_EXISTS',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
} as const;

export const POSTGRES_UNIQUE_VIOLATION = '23505';
