name: common
description: Shared widgets and utilities for Healytics applications.
publish_to: 'none'

version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Form
  flutter_form_builder: ^10.2.0
  shadcn_ui: ^0.35.0
  
  # Utilities
  intl: ^0.20.2
  fluttertoast: ^9.0.0
  
  # Tables
  data_table_2: ^2.7.2
  
  # Rich text
  flutter_quill: ^11.5.0
  
  # Images
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
